server:
  port: 8083
spring:
  application:
    name: file-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-postgresql-sgp1-93557-do-user-27848320-0.d.db.ondigitalocean.com:25060/file_service?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:doadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:AVNS_GP853Gug731-gzXfmnT}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
  data:
    redis:
      host: db-valkey-sgp1-50141-do-user-27848320-0.k.db.ondigitalocean.com
      port: 25061
      username: default
      password: AVNS_N-gwsyNb6xBC3fXPdQp
      ssl:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true
jwt:
  signerKey: ${JWT_SIGNERKEY:cnf61zcey4yE0RfDwk3yOAgi+CRVsjb1LPQP0O9e0GyLworFq8IthDFERD/0bxy2}
  valid-duration: ${JWT_VALID_DURATION:3600}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:86400}

file:
  max-size: 10MB
  s3:
    endpoint: ${S3_ENDPOINT:https://sgp1.digitaloceanspaces.com}
    region: ${S3_REGION:sgp1}
    bucket-name: ${S3_BUCKET_NAME:hla}
    access-key: ${S3_ACCESS_KEY:DO007GZR7WN63YHWKLVU}
    secret-key: ${S3_SECRET_KEY:LPB+xqPNyJ8RTN7Syg3932nDFqZOsGb2X3wa6jWV+yA}

app:
  default-admin-id: ${DEFAULT_ADMIN_ID:d50f8589-da20-49e8-a3f3-6a115d1f68d7}
