#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#
name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - be/dev

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      # Thêm permission 'security-events: write' để đẩy kết quả SARIF lên GitHub Security tab
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Không cần ref cụ thể, chỉ cần fetch toàn bộ lịch sử nếu cần quét sâu
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          linter: jetbrains/qodana-jvm-community:2025.2
          args: --project-dir,backend
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          # 2. Upload Báo cáo: Đặt 'upload-result' là 'true' để upload report HTML dưới dạng Artifact.
          upload-result: true
          push-fixes: 'none'
      - name: 'Upload SARIF to GitHub Security'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json